name: Test some actions

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  decide-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: ./.github/actions/define-release-version
        id: define-release-version

      - run: echo "The release version is ${{ steps.define-release-version.outputs.release_version }}"
