# Build a the loadbalancer binary on a release

name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
      id: go

    - name: Build
      run: go build -o lb cmd/lb.go
      id: build

    - name: Check build
      shell: bash
      run: |
        ls -al
        ./lb --help

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          # Release ${{ github.ref }}
          The new version of the loadbalancer has arrived! :rocket:
        # files: lb
