# Build a the loadbalancer binary on a release

name: Release

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  test:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    uses: LarsNieuwenhuizen/loadbalancer/.github/workflows/test.yml@main

  version:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      release_version: ${{ steps.info.outputs.release_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: ./.github/actions/define-release-version
        id: info

  build-and-release:
    runs-on: ubuntu-latest
    environment: Release
    needs:
      - version

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
      id: go

    - name: Build
      shell: bash
      run: ./build.sh ${{ needs.version.outputs.release_version }}

    - name: Check the created tarballs
      shell: bash
      run: |
        ls -al bin

    - name: Create a release commit
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "no-reply@email.com"
        git commit -m "release: ${{ needs.version.outputs.release_version }}" --allow-empty
        git push origin main --tags
        gh release create ${{ needs.version.outputs.release_version }} ./bin/*.tar.gz --generate-notes
